#!/usr/bin/python3
'''Made for python 3
This will generate a tables.md from tables.sql
'''

import re
from datetime import date

fsql = open('tables.sql', 'r')
ftxt = open('tables.md', 'w')

ftxt.write("# Table Documentation\n")
ftxt.write("Autogenerated based on tables.sql\n")
ftxt.write("Generated on "+ date.today().strftime("%d/%m/%Y"))
ftxt.write("\n\nPlease note for *YES/NO* columns:\n*YES* is stored as a **1**\n*NO* is stored as a **0**")

for line in fsql:
 if line[0:12] == "CREATE TABLE":
  ftxt.write("\n\n###**Tablename:** " + re.search(r"`.*`",line).group(0).replace('`', '*')+"\n")
 elif line[0:3] == "  `":
  ftxt.write("* " + re.search(r"`.*`",line).group(0).replace('`', '**'))
  if re.search(r"COMMENT",line) is not None:
   ftxt.write(re.search(r"COMMENT '.*",line).group(0).replace('COMMENT', ' -').replace("'", '*'))
  ftxt.write("\n")

fsql.close()
ftxt.close()
