#!/usr/bin/python3
'''Made for python 3
This will generate a tables.md from tables.sql
'''

import re
from datetime import date

fsql = open('tables.sql', 'r')
ftxt = open('tables.md', 'w')

#Header Info
ftxt.write("# Table Documentation\n")
ftxt.write("Autogenerated based on tables.sql")
ftxt.write("\n\nGenerated on "+ date.today().strftime("%d/%m/%Y"))
ftxt.write("\n\nPlease note for *YES/NO* columns: *YES* is stored as a **1** and *NO* is stored as a **0**")
ftxt.write("\n\n**REQ** means the value is required\n")

for line in fsql:
 #Place a generic line comment
 if line[0:3] == "-- ":
  ftxt.write("\n*" + line[3:-1] + "*\n\n")
 #Add H2 for a database creation
 elif line[0:15] == "CREATE DATABASE":
  ftxt.write("\n## **Database:** " + re.search(r"`.*`",line).group(0).replace('`', '*')+"\n")
 #Add H3 for a table creation
 elif line[0:12] == "CREATE TABLE":
  ftxt.write("\n### **Tablename:** " + re.search(r"`.*`",line).group(0).replace('`', '*')+"\n")
 #Find key/primary key of a table
 elif re.search(r"PRIMARY KEY.*\(`.*`\)",line) is not None:
  ftxt.write("\n*The following cannot be duplicated:* " + re.search(r"\(`.*`\)",line).group(0).replace('`', '**').replace('(', '').replace(')', '') + "\n")
 #Find column, assumed 2 space indent
 elif line[0:3] == "  `":
  ftxt.write("* " + re.search(r"`.*`",line).group(0).replace('`', '**'))

  #Find the value type
  if re.search(r"`.*`.*tinyint\(1\)",line) is not None:
   ftxt.write(" (0 or 1)")
  elif re.search(r"`.*`.*tinytext",line) is not None:
   ftxt.write(" (Text, up to 255 characters)")
  elif re.search(r"`.*`.*float",line) is not None:
   ftxt.write(" (Number Value)")
  elif re.search(r"`.*`.*int.*NOT.*NULL.*AUTO_INCREMENT",line) is not None:
   ftxt.write(" (Autogenerated Integer)")
  elif re.search(r"`.*`.*int",line) is not None:
   ftxt.write(" (Integer Value)")
  elif re.search(r"`.*`.*decimal\(",line) is not None:
   ftxt.write(" (Currency)")
  elif re.search(r"`.*` time",line) is not None:
   ftxt.write(" (Time)")
  elif re.search(r"`.*` date",line) is not None:
   ftxt.write(" (Date)")
  elif re.search(r"`.*`.*text",line) is not None:
   ftxt.write(" (Text)")

  #Show comment if available
  if re.search(r"COMMENT",line) is not None:
   ftxt.write(re.search(r"COMMENT '.*",line).group(0).replace('COMMENT', ' -').replace("'", '*'))

  #Show REQ if cannot be null
  if re.search(r"`.*`.* NOT NULL",line) is not None:
   ftxt.write(" **REQ**")

  ftxt.write("\n")

fsql.close()
ftxt.close()
