#!/usr/bin/python3
'''Made for python 3
This will generate a tables.md from tables.sql
'''

import re
from datetime import date

fsql = open('tables.sql', 'r')
ftxt = open('tables.md', 'w')

ftxt.write("# Table Documentation\n")
ftxt.write("Autogenerated based on tables.sql")
ftxt.write("\n\nGenerated on "+ date.today().strftime("%d/%m/%Y"))
ftxt.write("\n\nPlease note for *YES/NO* columns: *YES* is stored as a **1** and *NO* is stored as a **0**")

for line in fsql:
 if line[0:12] == "CREATE TABLE":
  ftxt.write("\n\n###**Tablename:** " + re.search(r"`.*`",line).group(0).replace('`', '*')+"\n")
 elif line[0:3] == "  `":
  ftxt.write("* " + re.search(r"`.*`",line).group(0).replace('`', '**'))
  
  if re.search(r"`.*`.*tinyint.(1.)",line) is not None:
   ftxt.write(" (0 or 1)")
  elif re.search(r"`.*`.*tinytext",line) is not None:
   ftxt.write(" (Text, up to 255 char)")
  elif re.search(r"`.*`.*float",line) is not None:
   ftxt.write(" (Number Value)")
  elif re.search(r"`.*`.*int.*NOT.*NULL.*AUTO_INCREMENT",line) is not None:
   ftxt.write(" (Autogenerated Integer)")
  elif re.search(r"`.*`.*int.(..)",line) is not None:
   ftxt.write(" (Integer Value)")
  elif re.search(r"`.*` time",line) is not None:
   ftxt.write(" (Time)")
  elif re.search(r"`.*` date",line) is not None:
   ftxt.write(" (Date)")
  elif re.search(r"`.*`.*text",line) is not None:
   ftxt.write(" (Text)")
   
  if re.search(r"COMMENT",line) is not None:
   ftxt.write(re.search(r"COMMENT '.*",line).group(0).replace('COMMENT', ' -').replace("'", '*'))
  ftxt.write("\n")

fsql.close()
ftxt.close()
